### ISSUE TITLE
Compatibility with macOS

### ISSUE THREAD

**Issue by PatrBal** [notmarek/SendToClient#4]
Hi,
I cannot make this work on macOS neither with Safari nor Chrome.
The problem is the same in both browsers. I can see that the script is enabled when I click the TamperMonkey icon in the browser. I also see the "Settings" item just below the enabled "SendToClient" item. The problem is that when I click on "Settings", nothing happens (no pop-up window appears as expected). 
I am also using the userscript "IMDb Scout Mod" on imdb.com, which also has a "Settings" menu item and this one works as expected on macOS (opening a pop-up window with all the settings of the userscript).
Any idea about what could be the origin of the problem?
Thanks in advance.

**Comment by PatrBal** [comment]
Thanks for your insight. I tried the script in ViolentMonkey on Chrome for macOS, without any more luck...

**Comment by notmarek** [comment]
Turns out it's a widespread issue with 2.3.0 please downgrade for the time being

**Comment by PatrBal** [comment]
Solved in version 2.3.1. It now works fine in TamperMonkey on macOS Safari. Thanks!
